service: <%- serviceName %>
frameworkVersion: ">=1.11.0 <2.0.0"
provider:
  name: aws
  runtime: nodejs6.10
  profile: ${self:custom.config.profile}
  region: <%- awsRegion %>

plugins:
  - serverless-plugin-aws-alerts
  - serverless-plugin-crypt
  - serverless-plugin-simulate

custom:
  config: ${file(./config/${opt:stage}.yml):config}

  crypt:
    aws:
      kmsKeyId: ${self:custom.config.kmsKeyId}

  alerts:
    stages:
      - production
    topics:
      ok:
        topic: ${self:service}-${opt:stage}-alerts-ok
      alarm:
        topic: ${self:service}-${opt:stage}-alerts-alarm
      insufficientData:
        topic: ${self:service}-${opt:stage}-alerts-insufficientData

package:
  exclude:
    - config/**
    - coverage/**
    - migrations/**
    - node_modules/**
    - src/package.json
    - src/**/*.test.js
    - .editorconfig
    - .env-*
    - .eslint*
    - .envrc
    - .gitignore
    - .node-version
    - .travis.yml
    - .yarnrc
    - '*.sh'
    - package.json
    - yarn.lock
    - README.md

functions:
  # hello:
  #   handler: src/hello

#resources:
#  Resources:
#  Outputs:
