service: <%- serviceName %>
provider:
  name: aws
  runtime: nodejs4.3

custom:
  packageEnv:
    fileName: .env-${opt:stage}

plugins:
  - serverless-plugin-package-dotenv-file
  - serverless-offline
  - serverless-run-function-plugin

package:
  exclude:
    - coverage/**
    - node_modules/**
    - src/package.json
    - test/**
    - .editorconfig
    - .env-*
    - .envrc
    - .eslint*
    - .gitignore
    - .node-version
    - .travis.yml
    - deploy.sh
    - install.sh
    - package.json
    - README.md

functions:
  hello:
    handler: src/index.hello

#resources:
#  Resources:
#  Outputs:
